# Generated by Django 5.0.6 on 2024-06-26 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prochat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mytest',
            name='Response_validated',
            field=models.CharField(max_length=10000),
        ),
    ]
