# Generated by Django 5.0.6 on 2024-06-29 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prochat', '0003_alter_mytest_response_validated'),
    ]

    operations = [
        migrations.CreateModel(
            name='mytest1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jon_Response', models.CharField(max_length=40000)),
            ],
        ),
    ]
